#!/usr/bin/env node
// Regenerates the in-file MAP block for large source files.
//
// For every .js/.jsx under src/ that is at least MIN_LINES long, this writes
// (or refreshes) a comment block near the top listing the file's functions in
// declaration order. The block is delimited by sentinels and is rewritten
// wholesale on each run, so it can never drift from the source — and it
// deliberately carries NO line numbers (those rot on the next edit); the names
// are the durable part, and you Grep a name to jump to it.
//
// Usage: npm run index   (or: node scripts/generate-index.mjs)

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const MIN_LINES = 300;

const START = '// === MAP (generated by `npm run index` — do not edit by hand) ===';
const END = '// === /MAP ===';

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(js|jsx)$/.test(name)) out.push(full);
  }
  return out;
}

// Strip any existing MAP block (and one trailing blank line) so reruns don't stack.
function stripExisting(lines) {
  const s = lines.findIndex((l) => l.trim() === START);
  if (s === -1) return lines;
  let e = lines.findIndex((l, i) => i >= s && l.trim() === END);
  if (e === -1) e = s;
  if (lines[e + 1] !== undefined && lines[e + 1].trim() === '') e++;
  return [...lines.slice(0, s), ...lines.slice(e + 1)];
}

// Insertion point = just after the leading import block (skipping blanks/comments).
function insertionIndex(lines) {
  let at = 0;
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (/^\s*import\b/.test(l)) {
      let j = i;
      while (j < lines.length && !/;\s*$/.test(lines[j]) && !/from\s+['"][^'"]+['"]/.test(lines[j])) j++;
      at = j + 1;
      i = j;
    } else if (l.trim() === '' || /^\s*\/\//.test(l)) {
      continue;
    } else {
      break;
    }
  }
  return at;
}

function collect(lines) {
  const topLevel = [];
  const internal = [];
  for (const l of lines) {
    let m;
    if ((m = /^(?:export\s+)?(?:async\s+)?function\s+([A-Za-z0-9_]+)/.exec(l))) topLevel.push(m[1]);
    else if ((m = /^(?:export\s+)?const\s+([A-Za-z0-9_]+)\s*=\s*(?:async\s*)?(?:\(|function\b|forwardRef\b|memo\b|React\.)/.exec(l))) topLevel.push(m[1]);
    else if ((m = /^\s+function\s+([A-Za-z0-9_]+)\s*\(/.exec(l))) internal.push(m[1]);
  }
  return { topLevel: [...new Set(topLevel)], internal: [...new Set(internal)] };
}

function buildBlock({ topLevel, internal }) {
  const out = [START];
  if (topLevel.length) out.push(`// exports/top-level: ${topLevel.join(' · ')}`);
  if (internal.length) out.push(`// internal: ${internal.join(' · ')}`);
  out.push(END);
  return out;
}

let updated = 0;
for (const file of walk(SRC)) {
  let lines = readFileSync(file, 'utf8').split('\n');
  const lineCount = lines.length;
  const hadBlock = lines.some((l) => l.trim() === START);
  if (lineCount < MIN_LINES && !hadBlock) continue;

  lines = stripExisting(lines);

  // If the file dropped below the threshold, leave it stripped (block removed).
  if (lines.length < MIN_LINES) {
    if (hadBlock) {
      writeFileSync(file, lines.join('\n'));
      console.log(`removed MAP (now ${lines.length} lines): ${relative(ROOT, file)}`);
      updated++;
    }
    continue;
  }

  const at = insertionIndex(lines);
  const block = buildBlock(collect(lines));
  const next = [...lines.slice(0, at), '', ...block, ...lines.slice(at)];
  writeFileSync(file, next.join('\n'));
  console.log(`mapped (${lineCount} lines): ${relative(ROOT, file)}`);
  updated++;
}

console.log(`\nDone. ${updated} file(s) updated.`);
